### ISSUE TITLE
Clean up run.py and dataset modules

### ISSUE THREAD

**Issue by shuttle1987** [oadams/persephone#36]
Currently modules such as dataset/chatino.py will not be able to be imported if the various files that are specified by config cannot be found.

This might be an issue if someone wants to run some files with one language but not chatino for example. Essentially we don't want people to get an error on import for code that they will not actually run. This is caused by code that is in the top level being executed when the module is imported. We could fix this by making sure that execution requiring paths to be specified only occurs when the functions in the module are called.

**Comment by shuttle1987** [comment]
Right now there's 2 functions that have a lot of duplicated functionality:
https://github.com/oadams/persephone/blob/b0cf86c3a0f7cd4fc656d213eb272ce2bf8073a0/persephone/run.py#L30

https://github.com/oadams/persephone/blob/b0cf86c3a0f7cd4fc656d213eb272ce2bf8073a0/persephone/run.py#L44

This could be improved by removing the duplicated logic.

**Comment by shuttle1987** [comment]
Currently being worked on in https://github.com/oadams/persephone/pull/49

**Comment by oadams** [comment]
I just removed the bug label because imports no longer fail. run.py still needs a clean-up. It was initially used to run experiments, but now it should just offer some experiment utilities to be called from elsewhere. Perhaps it should be renamed experiment.py

**Comment by shuttle1987** [comment]
This reminds me, it's a good practice to occasionally try to import every file in the project individually. This makes it possible to check for import errors, including more subtle ones that can be hidden by how importlib caches imports.

-------- Original message --------
