### ISSUE TITLE
Improve logging

### ISSUE THREAD

**Issue by oadams** [oadams/persephone#44]
I realise now this is super important. If people email in when the tool crashes, there might not be much to go on. Need to be able to request logs.

**Comment by shuttle1987** [comment]
At a very minimum you need to have unhandled exceptions logged. I wrote a tutorial on how to do that here: https://www.customprogrammingsolutions.com/tutorial/logging-uncaught-exceptions-python-applications

At first glance handling the threaded situation probably looks like overkill but it's really useful if later on people run multiple threads, which is something that has to happen in any GUI.

**Comment by shuttle1987** [comment]
Suitable for 1.0.0 milestone? https://github.com/oadams/persephone/milestone/1

**Comment by oadams** [comment]
Yes, good call!
