### ISSUE TITLE
Add an integration test for the tutorial

### ISSUE THREAD

**Issue by oadams** [oadams/persephone#67]
With substantial changes in the code base to take place, we need to ensure the tutorial keeps working end-to-end.

**Comment by shuttle1987** [comment]
I noticed while working on #71 that this test outputs the data to whatever the default path is. I suspect you don't want to output these tests to the default paths if other experiment data is there as it will contaminate testing with non-testing files. This is something where some other directory would be strongly preferable I suspect but would require you to change the paths to be received via parameters.

**Comment by oadams** [comment]
Yeah, this is something I noticed and good point. When finishing off the test to check for convergence I will make this change.
