### ISSUE TITLE
Make a custom decorator for pytest

### ISSUE THREAD

**Issue by oadams** [oadams/persephone#70]
Integration tests should only be run before releases, due to the computational demand. Ideally there should be something like: ``tox release`` for testing before releasing, and ``tox fast`` for quicker unit tests and linting during development.

Using pytest decorators to categorize tests is the way to do this.

**Comment by shuttle1987** [comment]
It's probably easier for me to just PR this than to explain here.

**Comment by shuttle1987** [comment]
Done here https://github.com/oadams/persephone/pull/71
