### ISSUE TITLE
Can't clone HimalCo subrepo

### ISSUE THREAD

**Issue by shuttle1987** [oadams/persephone#84]
Build is failing due to lack of ability to clone sub-repo: https://travis-ci.org/oadams/persephone/builds/342834243?utm_source=github_status&utm_medium=notification

**Comment by alexis-michaud** [comment]
Le dimanche 18 février 2018, Janis Lesinskis <notifications@github.com> a
écrit :
> Build is failing due to lack of ability to clone sub-repo:
https://travis-ci.org/oadams/persephone/builds/342834243?utm_source=github_status&utm_medium=notification
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci6.googleusercontent.com/proxy/NUBQ4BTvWWIP8azlCpl9pQNfWmfp25q2_iLZczaRUctmKmv5F4xaIJ_ra2tqHV9b6ktZhc1cK1xYvMcOK-uDghOhzDFAqUSXLTtbNz5Eis5RRetGBvE4ESxekZSPIHtWSZxVBSiye9OaiitFyuZ-WkjfJsqKKA=s0-d-e1-ft#https://github.com/notifications/beacon/AFyozB4OZYNFFzkGiPH-1dbZzfw6goLYks5tV4ehgaJpZM4SJinB.gif
>
Apologies for this: Himalco is not public
(planned to go public by end of 2018)

-- 
Alexis Michaud, CNRS researcher (Chargé de recherche)
LACITO <http://lacito.vjf.cnrs.fr/membres/michaud_en.htm>, centre
André-Georges Haudricourt
Adjunct member of *Laboratoire de Phonétique et Phonologie*, Paris
<http://lpp.in2p3.fr/>
Language documentation that I collect is available online in the Pangloss
Collection <http://lacito.vjf.cnrs.fr/pangloss/index_en.html>

**Comment by alexis-michaud** [comment]
What are the technical solutions in the meantime? 

Would it help if I moved the Na data to a public repository of my own (under my name)?

**Comment by alexis-michaud** [comment]
Here's an attempt (remember that I'm not an experimented GitHub user) : 

https://github.com/alexis-michaud/na-data

**Comment by shuttle1987** [comment]
It's great to see that you are working on more datasets. I want to be very clear that I would like this data to be supported, it's just a matter of how. My issue here is that a private repository can't be a dependency of a public library such as this, this is causing the build to fail. The way to tackle this would be to install this library then import the data you need separately. If that can't easily be done now please let us know so we can make the necessary improvements to this library. It indicates issues if data has to be included into the source tree of the library in order to be used, it would be better for us to fix the API to the library if this is necessary.

**Comment by alexis-michaud** [comment]
Hi Janis, good to be in touch. I have been following the exciting developments on Persephone in the past weeks.

Just to clarify, this is not a new dataset: the Yongning Na data is one of 2 sets with which initial tests were carried out: Na and Chatino. Now I've moved the Na data to a (new) public repository. It is now online.

https://github.com/alexis-michaud/na-data/commit/aeb93547563ac7af817f418b82c5886cc060054e

Now that the data is in a public library, like the code, does this solve the issue?

Many thanks & all best!

**Comment by alexis-michaud** [comment]
@oadams : a possible problem with hosting the Na data in this new repository is that one can't refer back to older commits in case someone wants to replicate an experiment that was done in 2017 on older states of this data set. Changes will be tracked only from today's initial commit). That may not be a big concern, though, and I'll leave a copy of 'heritage' data on HimalCo.

If move to this new repository makes sense, please let me know so I can tidy up the na-data repository, adding a welcoming ReadMe message &c.

**Comment by oadams** [comment]
Hi Janis, thanks for bringing this up. I added the submodule to keep record of which versions of the Na data I was using in experiments and for a big integration test I'm writing. (Alexis, yes this does still mean that old results from 2017 use slightly different preprocessing. However, what I used back then was Diep's preprocessing in any case.)

It seems like the correct thing to do is not have the HimalCo repo, as a submodule (or any other language data), and just require it to be handled directly by the integration test and any other experimental code. Any experimental code can just keep the hash of the relevant HimalCo commit for exact reproducability.

**Comment by oadams** [comment]
@alexis-michaud Oh, and thanks for putting that Na data in a public repo! For now that's what I'll put in the integration test so that my Github login isn't needed.

**Comment by shuttle1987** [comment]
I think there's an interesting learning opportunity here in that it shows how putting the data in the same repository makes it harder to change code into a library later on. I think that due to this choice being made earlier we are hampered somewhat now, but I think this has been handled very well by everyone involved. Going forward it might make sense to create a Github organization for storage of related repositories.
