### ISSUE TITLE
ELAN preprocessing needs to handle the TIME_ORIGIN attribute of MEDIA_DESCRIPTOR element

### ISSUE THREAD

**Issue by oadams** [oadams/persephone#87]
ELAN's .eaf XML files can specify an time offset with which to start the audio. The annotations in the file are all relative to this starting point. For non-zero offsets any automatic trimming will result in misaligned utterances. The obvious solution is to check for that attribute and adjust utterance extraction from WAV files accordingly.

@benfoley I'm currently making an ELANCorpus class to handle ELAN input files, but if you get a chance it would be a good to address this in your split_eafs.py script as well.

**Comment by benfoley** [comment]
Thanks for the heads-up!
