### ISSUE TITLE
Draw a distinction between slow tests and very slow tests

### ISSUE THREAD

**Issue by oadams** [oadams/persephone#94]
There are tests that are slow that involve pulling lots of data, performing preprocessing, training small models, etc. Then there are mega end-to-end tests which could take days to run on a CPU-only machine. These should be categorized differently slow that tox -- --slow is different from tox -- --veryslow.

Related note: I've started using the notravis mark for tests that can't be run on Travis. This is orthogonal to speed (.travis.yml doesn't run the slow tests anyway), and is mostly because they rely on data that is not public, or would require fixtures that last between builds.

**Comment by shuttle1987** [comment]
You could always make a `veryslow` test marker as well, then you can specify to run those tests only if that option is set.

**Comment by oadams** [comment]
I've thought a bit more about how to manage the experiments and this is what I've come up with:
- If no flags are set, then tests are run that are both fast to run and don't require authentication to access non-public data. These can be run on travis.
- `--notravis` activates tests designated with a `pytest.mark.notravis` mark that can't be run via Travis because they are a bit slower or require non-public data. However, these tests should in the slowest case complete in a few hours.
- `--experiment` is for reproducing experiments and most tests that involve assertions about the error rate reaching a given value. These are typically long-running experiments, taking days. I've made a `tests/experiments/` subdirectory mostly for tests marked with the relevant mark `pytest.mark.experiment`.

As many tests as possible should be run when no flags are specified.

An additional flag, `--preprocess` is orthogonal to the others and is used to force re-preprocessing of input data. If the purpose of the testing is to make sure the tests run end-to-end with the most recent preprocessing, then this flag should be set. In such cases, the test fixture responsible for preprocessing will request the data from online (where applicable) and perform preprocessing. (Ideally ensuring up-to-date preprocessing of data would be handled by checking hashes of input data and git commits, but this forced preprocessing should be an option in any case). Without this flag, tests will used cached data where available, which for the `--notravis` tests will speed things up considerably since preprocessing will typically be larger relative to training time than in the `--experiment` case.
